version: '3'

services:
  ejbca:
    image: primekey/ejbca-ce:latest
    container_name: ejbca-app
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=ejbca
      - MYSQL_DATABASE=ejbca
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    networks:
      - dockernetwork

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ejbca
      MYSQL_USER: ejbca
      MYSQL_PASSWORD: ejbca
    ports:
      - "3306:3306"
    networks:
      - dockernetwork

networks:
  dockernetwork:
    external: true

