apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
      - name: ejbca
        image: primekey/ejbca-ce:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: cert-user
        - name: DB_PASS
          value: passwd
        - name: DB_NAME
          value: cert
---
apiVersion: v1
kind: Service
metadata:
  name: ejbca-service
spec:
  selector:
    app: ejbca
  ports:
    - name: http
      protocol: TCP
      port: 7080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP

