apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ejbca
  template:
    metadata:
      labels:
        app: ejbca
    spec:
      containers:
      - name: ejbca
        image: primekey/ejbca-ce:latest
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: MYSQL_USER
          value: ejbca
        - name: MYSQL_PASSWORD
          value: ejbca
        - name: MYSQL_DATABASE
          value: ejbca
        - name: MYSQL_HOST
          value: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: ejbca-service
spec:
  selector:
    app: ejbca
  ports:
    - name: http
      protocol: TCP
      port: 7080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP

