apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
      server {
          listen 80;
          server_name secret.rlcosta.cloudns.ch;

          location / {
              return 301 https://$host$request_uri;
          }
      }

      server {
          listen 443 ssl;
          server_name secret.rlcosta.cloudns.ch;
          ssl_certificate /etc/nginx/certs/fullchain.pem;
          ssl_certificate_key /etc/nginx/certs/privkey.pem;

          location / {
              proxy_pass http://secret-service.default.svc.cluster.local:7143;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

      server {
          listen 443 ssl;
          server_name plik.rlcosta.cloudns.ch;

          ssl_certificate /etc/nginx/certs/fullchain.pem;
          ssl_certificate_key /etc/nginx/certs/privkey.pem;

          location / {
              proxy_pass http://plik-service.default.svc.cluster.local:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

      server {
          listen 80;
          server_name wiki.rlcosta.cloudns.ch;

          location / {
              return 301 https://$host$request_uri;
          }
      }

      server {
          listen 443 ssl;
          server_name wiki.rlcosta.cloudns.ch;
          ssl_certificate /etc/nginx/certs/fullchain.pem;
          ssl_certificate_key /etc/nginx/certs/privkey.pem;

          location / {
              proxy_pass http://wiki-service.default.svc.cluster.local:3000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

      server {
          listen 80;
          server_name cert.rlcosta.cloudns.ch;

          location / {
              rewrite ^/(.*)$ https://$server_name/ejbca/adminweb/$1 permanent;
          }
      }

      server {
          listen 443 ssl;
          server_name cert.rlcosta.cloudns.ch;

          ssl_certificate /etc/nginx/certs/fullchain.pem;
          ssl_certificate_key /etc/nginx/certs/privkey.pem;

          location /ejbca/adminweb {
              proxy_pass https://ejbca-service.default.svc.cluster.local:8443;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    }

#    stream {
#      server {
#         listen 5432;
#         proxy_pass postgres.default.svc.cluster.local:5432;
#      }
#    }

