apiVersion: v1
kind: Service
metadata:
  name: plik-fixed-service
spec:
  type: NodePort
  selector:
    app: plik
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Fixed NodePort

