apiVersion: apps/v1
kind: Deployment
metadata:
  name: plik-deployment
  labels:
    app: plik
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: plik
        octopusexport: OctopusExport
    spec:
      containers:
        - name: plik-app
          image: 'rlcosta121/plik-app:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
