apiVersion: apps/v1
kind: Deployment
metadata:
  name: plik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plik
  template:
    metadata:
      labels:
        app: plik
    spec:
      containers:
      - name: plik-container
        image: rlcosta121/plik-app:main
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # You can specify a port in the range 30000-32767
  type: NodePort
