apiVersion: apps/v1
kind: Deployment
metadata:
  name: plik-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plik
  template:
    metadata:
      labels:
        app: plik
    spec:
      containers:
      - name: plik-container
        image: rlcosta121/plik-app
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: plik-service
spec:
  selector:
    app: plik
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
