# secret-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
  labels:
    app: secret-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: secret-app
          image: rlcosta121/secret-app:latest
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: secret-service
spec:
  selector:
    app: secret-app
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP

