apiVersion: v1
kind: Service
metadata:
  name: secret-fixed-service
spec:
  type: NodePort
  selector:
    app: secret
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30003  # Fixed NodePort

