apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
      - name: secret
        image: dismantl/onetimesecret:latest
        ports:
        - containerPort: 7143
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: secret-user
        - name: DB_PASS
          value: passwd
        - name: DB_NAME
          value: secret

---
apiVersion: v1
kind: Service
metadata:
  name: secret-service
spec:
  selector:
    app: secret
  ports:
    - protocol: TCP
      port: 7143
      targetPort: 7143
  type: ClusterIP
