apiVersion: v1
kind: Service
metadata:
  name: wiki-fixed-service
spec:
  type: NodePort
  selector:
    app: wikijs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002  # Fixed NodePort

