apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: linuxserver/wikijs:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: wiki-user
        - name: DB_PASS
          value: passwd
        - name: DB_NAME
          value: wiki

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
spec:
  selector:
    app: wiki
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP


