# wiki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-app
  labels:
    app: wiki-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiki-app
  template:
    metadata:
      labels:
        app: wiki-app
    spec:
      containers:
        - name: wiki-app
          image: rlcosta121/wiki-app:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
spec:
  selector:
    app: wiki-app
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 3000
  type: ClusterIP

